modLoader="javafml"
loaderVersion="[47,)"
logoFile="raremoon.png"
license="All Rights Reserved"

[[mods]]
    modId="environs"
    version="1.0.0"
    displayName="Environs"
    credits="Special thanks to the generous help of the Forge/NeoForge Discord community!"
    authors="burnsqc"
    description='''Environs is a small client-only mod for Minecraft that displays title card overlays when chaging dimensions, biomes, and structures.'''

[[dependencies.environs]] 
    modId="forge" 
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.environs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"